[package]
name = "day01"
version = "0.1.0"
authors = ["Arnaud Rinquin <rinquin.arnaud@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"